openapi: 3.0.3
info:
  title: Library API
  version: 1.3.0
  description: STD22006
servers:
  - url: https://library.com
tags:
  - name: Books
  - name: Authors
paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDateMin
          description: |
            If `releaseDateMax` is not provided, `releaseDateMin` is ignored,
            `releaseDateMin` can not be after `releaseDateMax`
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: releaseDateMax
          description: |
            If `releaseDateMin` is not provided, `releaseDateMax` is ignored.
            `releaseDateMax` can not be before `releaseDateMin`
          required: false
          schema:
            type: string
            format: date    
        - $ref: "#/components/parameters/queryPagination" 
      responses:
        '200':
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        '500':          
          $ref: '#/components/responses/500'          
    put:
      tags:
        - Books
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CrupdateBook"
      responses:
        '200':
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        '500':
          $ref: '#/components/responses/500'          
    # Delete many books
    delete:
      tags:
        - "Books"
      summary: Delete one or many book(s)
      operationId: deleteManyBooks
      requestBody:
        description: The list of book's ID
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: The book(s) deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        '500':
          $ref: '#/components/responses/404'                     
  /books/{bookId}:
    delete:
      tags:
        - Books
      summary: Delete a book
      operationId: deleteBook
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The book deleted
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'  
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - "Books"
      summary: Moify the book's author
      operationId: modifyBookAuthor
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The book modified with their author
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        '500':
          $ref: '#/components/responses/500'                           
  /books/authors/:
    put:
      tags:
        - "Authors"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBookAuthor"
      responses:
        '200':
          description: The book's author updated
        '500':
          $ref: '#/components/responses/500'  
  /books/import:
    post:
      tags:
        - "Books"
      summary: Import book(s)
      description: Import a list of books
      operationId: importBook
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CrupdateBook"
      responses:
        '200':
          description: The list of imported books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        '500':
          $ref: '#/components/responses/500'          
                
  /authors:
    get:
      tags:
        - Authors
      summary: Get all authors
      description: The returned author are ordered by updated datetime.
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: |
            Filter returned author by given name.
            If not provided, then list is not filterd.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: The list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        '500':
          $ref: '#/components/responses/500'          
    put:
      tags:
        - Authors
      summary: Create or update a list of authors
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
      responses:
        '200':
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        '500':
          $ref: '#/components/responses/500'        
   # TODO(Vid√©o): Delete many authors
    delete:
      tags:
        - "Authors"
      summary: Delete one or many authors
      operationId: deleteManyAuthors
      requestBody:
        description: The list of author's ID
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: The author(s) deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        '404':          
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'         
  /authors/{authorId}:
    delete:
      tags:
        - Authors
      summary: Delete an author
      operationId: deleteAuthor
      parameters:
        - name: authorId
          description: Author identifier to be deleted
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The author deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Author"
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /authors/page/{pageNumber}/size/{pageSize}:
    get:
      tags:
        - "Authors"
      summary: "The returned authors are paginated by page number and page size"   
      operationId: getPaginatedAuthors
      parameters:
        - $ref: "#/components/parameters/pathPageNumber"
        - $ref: "#/components/parameters/pathPageSize"
      responses:
        '200':
          description: "The list of filtered and paginated authors"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        '500':
          $ref: '#/components/responses/500'               
  /authors/import:
    post:
      tags:
        - "Authors"
      summary: Import author(s)
      description: Import a list of authors
      operationId: importAuthor
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
      responses:
        '200':
          description: The list of imported authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        '500':
          $ref: '#/components/responses/500'          

components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
    Sex:
      type: string
      enum:
        - M
        - F
    Book:
      type: object
      allOf:
        - $ref: '#/components/schemas/CrupdateBook'
      properties:
        author:
          $ref: '#/components/schemas/Author'
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: string
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER)
        releaseDate:
          type: string
          format: date
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string
    Status:
      type: object
      properties:
        code:
          type: integer
          enum:
            - 200
            - 400
            - 403
            - 500
        message:
          type: string
    Body:
      type: object
      properties:
        returned:
          type: object
    Response:
      type: object
      allOf:
        - $ref: "#/components/schemas/Status"
        - $ref: "#/components/schemas/Body"
    ImportAuthor:
      type: array
      items:
        type: object
        properties:
          authorName: 
            $ref: "#/components/schemas/Author/properties/name"
          sex:
            $ref: "#/components/schemas/Author/properties/id"
    ImportBook:
      type: array
      items:
        type: object
        properties:
          bookName:
            $ref: "#/components/schemas/CrupdateBook/properties/bookName"
          author: 
            $ref: "#/components/schemas/Author"
          topic:
            $ref: "#/components/schemas/CrupdateBook/properties/topic"

  parameters:
    queryPagination:
      name: queryPgParam
      in: query
      required: false
      schema:
        type: object
        properties:
          pageNumber:
            type: integer
            default: 1
          pageSize:
            type: integer
            default: 50
    pathPagination:
      name: pathPgParam
      in: path
      required: true
      schema:
        type: object
        properties:
          pageNumber:
            type: integer
            default: 1
          pageSize:
            type: integer
            default: 50
    pathPageNumber:
      in: path
      name: pageNumber
      required: true
      schema:
        type: integer
        default: 1
    pathPageSize:
      in: path
      name: pageSize
      required: true
      schema:
        type: integer
        default: 50
  responses:
    '400':
      description: Bad request exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example:
            code: 400
            message: Bad request error
            returned: null
    '403':
      description: Forbidden exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example:
            code: 403
            message: Forbidden error
            returned: null
    '404':
      description: Not found exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example:
            code: 404
            message: Not found error
            returned: null
    '500':
      description: Internal server error exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          example:
            code: 500
            message: Internal server error
            returned: null              
        



    

    
